# -*- coding: utf-8 -*-
"""
Created on 2024-07-10 11:57:47
---------
@summary:
---------
@author: root
"""

from feapder import UpdateItem


class BuffItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i buff
    """

    __table_name__ = "buff"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.appid = None
        self.bookmarked = None
        self.buy_max_price = None
        self.buy_num = None
        self.can_bargain = None
        self.can_search_by_tournament = None
        self.description = None
        self.game = None
        self.steam_price = None
        self.steam_price_cny = None
        self.has_buff_price_history = None
        self.item_id = None
        self.market_hash_name = None
        self.market_min_price = None
        self.name = None
        self.quick_price = None
        self.sell_min_price = None
        self.sell_num = None
        self.sell_reference_price = None
        self.short_name = None
        self.steam_market_url = None
        self.transacted_num = None
