# -*- coding: utf-8 -*-
"""
Created on 2024-07-05 17:07:16
---------
@summary:
---------
@author: pc
"""

from feapder import Item


class SteamNamesItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i steam_names
    """

    __table_name__ = "steam_names"

    __unique_key__ = ["game", "market_hash_name"]

    def __init__(self, *args, **kwargs):
        self.game = None
        # self.id = None
        self.market_hash_name = None
