# -*- coding: utf-8 -*-
"""
Created on 2024-07-05 17:10:44
---------
@summary:
---------
@author: pc
"""

from feapder import Item


class SteamNamesIdsItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i steam_names_ids
    """

    __table_name__ = "steam_names_ids"

    __unique_key__ = ["game", "item_nameid", "market_hash_name"]

    def __init__(self, *args, **kwargs):
        self.game = None
        # self.id = None
        self.item_nameid = None
        self.market_hash_name = None
