# -*- coding: utf-8 -*-
"""
Created on 2024-07-08 08:55:09
---------
@summary:
---------
@author: pc
"""

from feapder import UpdateItem


class SteamGraphItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i steam_graph
    """

    __table_name__ = "steam_graph"

    def __init__(self, *args, **kwargs):
        self.buy_order_graph = None
        # self.id = None
        self.item_nameid = None
        self.market_hash_name = None
        self.sell_order_graph = None
